model_config:
  hotpot_net:
    losses:
    - type: m4c_decoding_bce_with_mask

dataset_config:
  textvqa_hotpot:
    object_clsname_path: ${env.data_dir}/1600-400-20/objects_vocab.txt
    annotations:
      train:
        - imdb/m4c_textvqa/imdb_train_ocr_en.npy
      val:
        - imdb/m4c_textvqa/imdb_val_ocr_en.npy
      test:
        - imdb/m4c_textvqa/imdb_test_ocr_en.npy
    features:
      train:
#      - textvqa/defaults/features/open_images/detectron.lmdb,textvqa/ocr_en/features/ocr_en_frcn_features.lmdb
      - feat_resx/train/,ocr_feat_resx/textvqa_conf/train_images
      val:
#      - textvqa/defaults/features/open_images/detectron.lmdb,textvqa/ocr_en/features/ocr_en_frcn_features.lmdb
      - feat_resx/train/,ocr_feat_resx/textvqa_conf/train_images
      test:
#      - textvqa/defaults/features/open_images/detectron.lmdb,textvqa/ocr_en/features/ocr_en_frcn_features.lmdb
      - feat_resx/test/,ocr_feat_resx/textvqa_conf/test_images
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          max_seq_length: 20
      answer_processor:
        type: m4c_answer
        params:
          vocab_file: m4c_vocabs/textvqa/fixed_answer_vocab_textvqa_5k.txt
          preprocessor:
            type: simple_word
            params: {}
          context_preprocessor:
            type: simple_word
            params: {}
          max_length: 100
          max_copy_steps: 12
          num_answers: 10
      copy_processor:
        type: copy
        params:
          obj_max_length: 100
          max_length: 100
      phoc_processor:
        type: phoc
        params:
          max_length: 100
      context_processor:
        params:
          max_length: 100
      ocr_token_processor:
        type: simple_word
        params: {}
    return_features_info: true
    use_ocr: true
    use_ocr_info: true
    use_order_vectors: true

optimizer:
  params:
    eps: 1.0e-08
    lr: 1e-4
    weight_decay: 0
  type: Adam

evaluation:
  metrics:
  - textvqa_accuracy

training:
    clip_norm_mode: all
    clip_gradients: true
    max_grad_l2_norm: 0.25
    lr_scheduler: true
    lr_steps:
    - 14000
    - 19000
    lr_ratio: 0.1
    use_warmup: true
    warmup_factor: 0.2
    warmup_iterations: 1000
    max_updates: 24000
    batch_size: 2
    num_workers: 4
    task_size_proportional_sampling: true
    early_stop:
      criteria: textvqa/textvqa_accuracy
      minimize: false
